### ISSUE TITLE
idoc watch 没有反应失灵了。

### ISSUE THREAD

**Issue by wangchuxi** [jaywcjlove/idoc#1]
idoc v0.1.1 版本中，命令行中运行idoc watch 没有反应。

**Comment by jaywcjlove** [comment]
此功能依赖于操作系统底层提供的方法来监视文件系统的变化。

fs.watch 不是完全跨平台的，且在某些情况下不可用。


```
在 Linux 操作系统上，使用 inotify。
在 BSD 操作系统上 (包括 OS X)，使用 kqueue。
在 SunOS 操作系统上 (包括 Solaris 和 SmartOS)，使用 event ports。
在 Windows 操作系统上，该特性依赖于 ReadDirectoryChangesW。
```
如果系统底层函数出于某些原因不可用，那么 fs.watch 也就无法工作。例如，监视网络文件系统(如 NFS, SMB 等)的文件或者目录，就时常不能稳定的工作，有时甚至完全不起作用。
