### ISSUE TITLE
建议提供主题的插件机制

### ISSUE THREAD

**Issue by GuoYongfeng** [jaywcjlove/idoc#13]
今天闲来想自定义一个主题，看了提供的文档，看的不是特别清晰。想自定义导航的部分，发现提供出来的接口是封装好的html片段了。

所以建议提供一个用户自定义封装主题的机制，并且提供导航和文章主体等接口。这样大家都能参与进来丰富基于idoc的主题制作了。

**Comment by jaywcjlove** [comment]
没有问题 👌

**Comment by jaywcjlove** [comment]
重构已经支持主题自定义，提供变量接口
