### ISSUE TITLE
移动端导航不能响应式

### ISSUE THREAD

**Issue by GuoYongfeng** [jaywcjlove/idoc#14]
文章内容在移动端的阅读体验很赞，但是导航部分全部错乱了，建议把logo放在导航左上角，导航右上角放一个点击按钮的icon，点击后下拉或是右侧滑动展示导航的菜单。这样在移动端就太赞了。

**Comment by jaywcjlove** [comment]
@GuoYongfeng  👌

**Comment by jaywcjlove** [comment]
@GuoYongfeng 默认的主题，可以响应了
