### ISSUE TITLE
segmentfault文章右侧导航

### ISSUE THREAD

**Issue by GuoYongfeng** [jaywcjlove/idoc#19]
看到@jaywcjlove 也经常逛segmentfault，有木有觉得他们的文章的右侧文章目录部分很性感，鼠标向下滑动时自动定位到右侧的某个目录，且目录一直定位于右侧可视区内。这种体验比较nice，期待idoc也有这样的实现，就碉堡了。

**Comment by jaywcjlove** [comment]
嗯，现在做个自动生成简历的功能，导出PDF 。慢慢做
