### ISSUE TITLE
改进交流

### ISSUE THREAD

**Issue by GuoYongfeng** [jaywcjlove/idoc#2]
idoc很好用，同时也发现几个改进的点：

- 当菜单栏过长的时候，换行了，样式错乱
- 制定几种不同的风格可以选择，目前只有default
- 如果支持二级目录或三级目录，第一个问题就很帅气的解决了

**Comment by jaywcjlove** [comment]
嗯，可以的

1. 风格设计正在计划中。
2. 菜单理论上是无限极，但是我没有写样式，回头我调整以下。


样式错乱能截图上来我看看吗？

@GuoYongfeng

**Comment by GuoYongfeng** [comment]
一图胜千言

1. 写了个很长名字的文件，因为考虑可能后面一个目录会有很多个文件，导航排不下
2. 测试的代码目录


郭永峰
用友集团UAP中心
用友软件股份有限公司 yonyou software Co., Ltd.
电话 (Tel)：010-62432487
手机（Phone）: 13552329235
邮箱 (Mail)：guoyff@yonyou.com
地址：北京海淀区北清路 68 号 用友软件园 (邮编：100094)
Add: Yonyou Software Park, No. 68 Beiqing Road, Haidian District, Beijing, China 100094
网址 (Web): www.yonyou.com
 
发件人： kenny.wang
发送时间： 2015-10-14 20:42
收件人： jaywcjlove/idoc
抄送： GuoYongfeng
主题： Re: [idoc] 改进交流 (#2)
嗯，可以的
风格设计正在计划中。
菜单理论上是无限极，但是我没有写样式，回头我调整以下。
样式错乱能截图上来我看看吗？
@GuoYongfeng

**Comment by jaywcjlove** [comment]
@GuoYongfeng  第二个主题制作完成。
提供两个选择主题，default和handbook。

换主题瞬间的事儿。`idoc theme`  调出选择命令，选择之后自动生成。

[详情](http://jaywcjlove.github.io/idoc/html/%E4%B8%BB%E9%A2%98.html)

**Comment by GuoYongfeng** [comment]
nice



郭永峰
用友集团UAP中心
用友软件股份有限公司 yonyou software Co., Ltd.
电话 (Tel)：010-62432487
手机（Phone）: 13552329235
邮箱 (Mail)：guoyff@yonyou.com
地址：北京海淀区北清路 68 号 用友软件园 (邮编：100094)
Add: Yonyou Software Park, No. 68 Beiqing Road, Haidian District, Beijing, China 100094
网址 (Web): www.yonyou.com
 
发件人： kenny.wang
发送时间： 2015-10-26 10:02
收件人： jaywcjlove/idoc
抄送： GuoYongfeng
主题： Re: [idoc] 改进交流 (#2)
@GuoYongfeng 第二个主题制作完成。
提供两个选择主题，default和handbook。
换主题瞬间的事儿。idoc theme 调出选择命令，选择之后自动生成。
详情
