### ISSUE TITLE
建议:能否有个替换设置

### ISSUE THREAD

**Issue by seekwe** [jaywcjlove/idoc#27]
话说能否有个替换机制,比如
`[常用方法](常用方法.md)`

生成html的时候
`<a href="常用方法.md">常用方法</a>`

会导致链接(⊙_⊙)?(其实这是看云文档的)

请忽略

**Comment by seekwe** [comment]
其实更想问能否忽略某个文件不生成

**Comment by jaywcjlove** [comment]
这个是 markdown 语法，你要忽略里面某个连接....
