### ISSUE TITLE
可以考虑添加目录收起，否则子标题太多不太好查找

### ISSUE THREAD

**Issue by JakeLaoyu** [jaywcjlove/idoc#29]

**Comment by maskleo** [comment]
这个建议可以，表示支持下。

**Comment by jaywcjlove** [comment]
最近没有空搞呢 @JakeLaoyu

**Comment by JakeLaoyu** [comment]
@jaywcjlove 有时间看下

**Comment by jaywcjlove** [comment]
- [ ] 使用配置自定义顺序和子子菜单https://github.com/jaywcjlove/idoc/blob/15827c511ab43899b0a49490db11834c5cdaadef/rdoc.chapters.yml#L1-L5
- [ ] 放置到侧边展示子菜单。
