### ISSUE TITLE
idoc init 报错

### ISSUE THREAD

**Issue by yzxinbj** [jaywcjlove/idoc#30]
![image](https://cloud.githubusercontent.com/assets/20542958/21740553/a352564a-d4f7-11e6-8905-93417f9c561e.png)

**Comment by jaywcjlove** [comment]
sorry 没有在windows上面做测试，我没有windows系统...

**Comment by leichao998877** [comment]
我的也是在win7下报错

**Comment by jaywcjlove** [comment]
@leichao998877 nodejs 版本，idoc 版本

**Comment by jaywcjlove** [comment]
@leichao998877 @yzxinbj 

```bash
+ idoc@0.3.0
```
