### ISSUE TITLE
导航菜单是按照字母顺序排队,能自定义吗

### ISSUE THREAD

**Issue by koreabright** [jaywcjlove/idoc#32]

**Comment by jaywcjlove** [comment]
不能呢

**Comment by jaywcjlove** [comment]
```
$ npx idoc@1.0.0-beta.10 init myapp
```

- [x] v1 版本导航菜单将使用配置文件定义。
   - https://github.com/jaywcjlove/idoc/blob/15827c511ab43899b0a49490db11834c5cdaadef/rdoc.yml#L34-L36
- [ ] 子菜单在 v0.3 中使用下来菜单展示，导致菜单过长，在 v1 中使用[配置](https://github.com/jaywcjlove/idoc/blob/15827c511ab43899b0a49490db11834c5cdaadef/rdoc.chapters.yml#L1-L5) 自定义顺序和放置到侧边展示。 #29
  - [ ] 使用配置自定义顺序和子子菜单https://github.com/jaywcjlove/idoc/blob/15827c511ab43899b0a49490db11834c5cdaadef/rdoc.chapters.yml#L1-L5
  - [ ] 放置到侧边展示子菜单。 #29
