### ISSUE TITLE
Markdown 语法中的“苗点”无法正确在html中解释

### ISSUE THREAD

**Issue by maskleo** [jaywcjlove/idoc#35]
例如：

https://github.com/Radical-Acmen/java-snippets/blob/gh-pages/README.md

`back to top` 苗点在`md`文件中是返回到苗点
但是生成的html并不能返回到苗点

http://java-snippets.javaos.cc/

**Comment by jaywcjlove** [comment]
标题添加了`t2`

```markdown
[back to top](#t2Table of Contents)
```

**Comment by maskleo** [comment]
没明白您说的意思，正确的写法应该是？
最好同时支持`Markdown`和编译后的`html`
能否有一个实例？

**Comment by jaywcjlove** [comment]
@maskleo 正在撸一个新的文档工具  [jaywcjlove/rdoc](https://github.com/jaywcjlove/rdoc)

**Comment by maskleo** [comment]
@jaywcjlove 期待
