### ISSUE TITLE
升级到0.2.1下后idoc server无法正常启动（windows下）

### ISSUE THREAD

**Issue by GuoYongfeng** [jaywcjlove/idoc#5]
$ idoc server
c:\Program Files\nodejs\node_global\node_modules\idoc\node_modules\ssr\index.js:117
    var pt = argv.port || __port;
                 ^
TypeError: Cannot read property 'port' of undefined

**Comment by jaywcjlove** [comment]
@GuoYongfeng  修复 打了新版本   v0.2.2
