### ISSUE TITLE
idoc -s运行时如果修改文件报错停止运行

### ISSUE THREAD

**Issue by GuoYongfeng** [jaywcjlove/idoc#6]
$ idoc -s
Waiting...
idoc is running. Press Ctrl+C to stop.

  Static file server running at

=> http://localhost:1987

Initial scan complete. Ready for changes.

fs.js:747
  return binding.mkdir(pathModule._makeLong(path),
                 ^
Error: ENOENT, no such file or directory 'd:\website\MyTechBook\html\d:\website\MyTechBook\md\鎶€鏈垎浜?

**Comment by GuoYongfeng** [comment]
idoc -w会出现同样情况，0.1.4版本是正常的。

**Comment by jaywcjlove** [comment]
@GuoYongfeng 更新最新版本 0.2.3 都修复了。

**Comment by GuoYongfeng** [comment]
我的是windows，更新到最新版本还是不行。
fs.js:747
  return binding.mkdir(pathModule._makeLong(path),
                 ^
Error: ENOENT, no such file or directory 'd:\website\MyTechBook\html\d:\website\MyTechBook\md\鎶€鏈垎浜?
解析路径的时候会有问题



郭永峰
用友集团UAP中心
用友软件股份有限公司 yonyou software Co., Ltd.
电话 (Tel)：010-62432487
手机（Phone）: 13552329235
邮箱 (Mail)：guoyff@yonyou.com
地址：北京海淀区北清路 68 号 用友软件园 (邮编：100094)
Add: Yonyou Software Park, No. 68 Beiqing Road, Haidian District, Beijing, China 100094
网址 (Web): www.yonyou.com
 
发件人： kenny.wang
发送时间： 2015-10-26 21:48
收件人： jaywcjlove/idoc
抄送： GuoYongfeng
主题： Re: [idoc] idoc -s运行时如果修改文件报错停止运行 (#6)
Closed #6.

**Comment by jaywcjlove** [comment]
@GuoYongfeng 在window中，中文乱造成的？我测试一下。

**Comment by jaywcjlove** [comment]
@GuoYongfeng 亲测这个在windows上真的能用了，window 是个蛋疼的玩意儿。
