### ISSUE TITLE
导航栏HOME与ABOUT不显示

### ISSUE THREAD

**Issue by imtsy** [jaywcjlove/idoc#72]
部署成功之后，右上角的**HOME**和**ABOUT**均不显示，检查`idoc.yml`中`menus`设置正常。
<img width="400" alt="image" src="https://user-images.githubusercontent.com/97822258/236684527-cad17995-7fdb-47d5-88b3-971ec430de12.png">

**Comment by jaywcjlove** [comment]
@imtsy 如果你提供源码，我帮你调试一下

**Comment by imtsy** [comment]
这里是[源码](https://github.com/imtsy/imtsy.github.io)。
我将它部署在了原始的**Github Pages**上，所以我并没有切换分支。
由于**GitHub Pages**在部署的时候只能选择`main`分支下的`docs`文件夹，所以我将`docs`与`dist`文件夹互换了。
感谢😀

**Comment by imtsy** [comment]
> @imtsy 如果你提供源码，我帮你调试一下

这里是[源码](https://github.com/imtsy/imtsy.github.io)。
我将它部署在了原始的**Github Pages**上，所以我并没有切换分支。
由于**GitHub Pages**在部署的时候只能选择`main`分支下的`docs`文件夹，所以我将`docs`与`dist`文件夹互换了。
感谢😀

**Comment by jaywcjlove** [comment]
```diff
- data: 
-  menus:
-    Home: index.html
+ menus:
+   Home: index.html
```

@imtsy 我的模板错误，配置文件优化模版文件没有改过来
